sudo: required
language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - "12"
services:
  - docker

stages:
- name: dependencies
  if: (branch = master)
- name: test
  if: (branch = master)
- name: build
  if: (branch = master)
- name: deploy
  if: (branch = master)

jobs:
  include:
    - stage: dependencies
      script:
        - yarn install
    - stage: test
      script:
        - yarn test
    - stage: build and deploy
      before_script:
        # install heroku CLI
        - wget -qO- https://toolbelt.heroku.com/install.sh | sh
        # login to docker registries (dockerhub and heroku)
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
        # push to dockerhub
        - yarn build:docker
        - docker tag $DOCKER_USERNAME/blog-api:latest registry.heroku.com/$HEROKU_APP/web
      script: 
        - docker push $DOCKER_USERNAME/blog-api
        - docker push registry.heroku.com/$HEROKU_APP/web
        - heroku container:release web --app $HEROKU_APP
