sudo: required
language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - "12"

stages:
- name: dependencies
- name: test
- name: build
- name: build and deploy
  if: (branch = master)

jobs:
  include:
    - stage: dependencies
      name: "dependencies"
      script:
        - yarn install

    - stage: test
      name: "test unit"
      script:
        - yarn test

    - stage: test
      services:
        - postgresql
      name: "test e2e"
      script:
        - yarn test:e2e

    - stage: build and deploy
      name: deploy
      services:
        - docker
      before_script:
        # install heroku CLI
        - wget -qO- https://toolbelt.heroku.com/install.sh | sh
        # login to docker registries (dockerhub and heroku)
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
        # push to dockerhub
        - yarn build:docker
        - docker tag $DOCKER_USERNAME/blog-api:latest registry.heroku.com/$HEROKU_APP/web
      script: 
        - docker push $DOCKER_USERNAME/blog-api
        - docker push registry.heroku.com/$HEROKU_APP/web
        - heroku container:release web --app $HEROKU_APP
