sudo: required
language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - "12"
services:
  - docker

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

install:
  # install deps
  - yarn install

# script:
  # - yarn linter
  # - yarn test:ci
  # build docker images
  # - yarn build:docker
  # - docker tag $DOCKER_USERNAME/blog-api:latest registry.heroku.com/$HEROKU_APP/web

stages:
- name: dependencies
  if: (branch = master)
- name: test
  if: (branch = master)
- name: build
  if: (branch = master)
- name: deploy
  if: (branch = master)

jobs:
  include:
    - stage: dependencies
      script:
      yarn install
    - stage: test
      script:
      yarn test
    - stage: build
      script: 
      # push to dockerhub
      yarn build:docker;
      docker tag $DOCKER_USERNAME/blog-api:latest registry.heroku.com/$HEROKU_APP/web;
      docker push $DOCKER_USERNAME/blog-api;
    - stage: deploy
      script:
      docker push registry.heroku.com/$HEROKU_APP/web;
      heroku container:release web --app $HEROKU_APP




# deploy:
#   provider: script
#   script: 
#     # push to dockerhub & heroku
#     # docker push $DOCKER_USERNAME/blog-api;
#     docker push registry.heroku.com/$HEROKU_APP/web;
#     heroku container:release web --app $HEROKU_APP
#   on:
#     branch: master